### ISSUE TITLE
Addon would not launch on 10.1 Steam Version due to missing PySide2

### ISSUE THREAD

**Issue by fusion-9** [ynput/ayon-substance-painter#14]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior:

Add-on would not launch on 10.1 Steam Version due to missing PySide2

### Expected Behavior:

Run without errors

### Version

1.0.0

### What platform you are running on?

Linux / Ubuntu

### Steps To Reproduce:

Opening the program as per usual.

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the bug report.

### Relevant log output:

```shell
[Python] Failed to start plugin ayon_plugin
[Python] Traceback (most recent call last):
  File "/media/terry/GAMING/SteamLibrary/steamapps/common/Substance 3D Painter 2024/resources/python/startup/painter_plugins_ui.py", line 58, in manage_plugin
    substance_painter_plugins.reload_plugin(module)
  File "/media/terry/GAMING/SteamLibrary/steamapps/common/Substance 3D Painter 2024/resources/python/modules/substance_painter_plugins.py", line 157, in reload_plugin
    start_plugin(module)
  File "/media/terry/GAMING/SteamLibrary/steamapps/common/Substance 3D Painter 2024/resources/python/modules/substance_painter_plugins.py", line 88, in start_plugin
    module.start_plugin()
  File "/home/terry/.local/share/AYON/addons/substancepainter_0.2.1/ayon_substancepainter/deploy/plugins/ayon_plugin.py", line 26, in start_plugin
    install_host(SubstanceHost())
  File "/home/terry/.local/share/AYON/addons/core_0.4.4/ayon_core/pipeline/context_tools.py", line 129, in install_host
    host.install()
  File "/home/terry/.local/share/AYON/addons/substancepainter_0.2.1/ayon_substancepainter/api/pipeline.py", line 74, in install
    self._install_menu()
  File "/home/terry/.local/share/AYON/addons/substancepainter_0.2.1/ayon_substancepainter/api/pipeline.py", line 165, in _install_menu
    from PySide2 import QtWidgets
ModuleNotFoundError: No module named 'PySide2'
```

### Additional context:

At least the plugin shows up in the Python panel, I tried to install PySide in a similar to the Blender Addon guide but I broke the program and had to reinstall.

Another thing is that even if I don't open Painter from the AYON Launcher I still get the error and the Plugin trying to load.

**Comment by fusion-9** [comment]
UPDATE: I deleted the a python cache that was laying around and now the plugin doesn't try to load anymore, the main issue is still there.

**Comment by BigRoy** [comment]
Thanks for reporting @fusion-9 - this is actually fixed very recently here: https://github.com/ynput/ayon-substance-painter/pull/12

As such, if you run the package from a develop build it should now work - yet a new release has still to be made so it's not on AYON addon market yet.
